name: Auto Dataset Versioning

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
        tags:
          description: 'Manual run'  
  push:
    branches:
      - 'main'
    paths:
      - 'create_wandb_dataset.ipynb'  # Only trigger if modelling.ipynb changes

jobs:
  run-jupyter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Install everything needed for your notebook:
          pip install -r requirements.txt 
          pip install jupyter nbconvert

      - name: Export GitHub secret to env
        # This takes your MY_SECRET GitHub secret and makes it available as an env variable
        run: |
          echo "DATA_URL=${{ secrets.DATA_URL }}" >> $GITHUB_ENV
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" >> $GITHUB_ENV
          echo "DATASET_DICT=${{ secrets.DATASET_DICT }}" >> $GITHUB_ENV
          echo "ARTIFACT_DIR=${{ secrets.ARTIFACT_DIR }}" >> $GITHUB_ENV

      - name: Run Jupyter Dasaset Notebook
        run: |
          # Execute the notebook. 
          # If the notebook includes code that uses MY_SECRET, it can read it from the env.
          jupyter nbconvert --to notebook --execute create_wandb_dataset.ipynb --output executed_create_wandb_dataset.ipynb
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dataset-artifact
          path: executed_create_wandb_dataset.ipynb

      - name: Run Jupyter Model Notebook
        run: |
          # Execute the notebook. 
          # If the notebook includes code that uses MY_SECRET, it can read it from the env.
          jupyter nbconvert --to notebook --execute modeling.ipynb --output executed_modeling.ipynb
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: modeling-artifact
          path: executed_modeling.ipynb
